services:
  postgres-order:
    image: postgres:15
    container_name: orderservice-db
    environment:
      POSTGRES_DB: orderservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data

volumes:
  order_postgres_data: